### ISSUE TITLE
Crystal 0.23.0 breaking Crecto?

### ISSUE THREAD

**Issue by johnnygreen** [Crecto/crecto#102]
Hello,

Sorry repost, I was logged in to the wrong account.

Warning - I just started using Crystal last week, so forgive me if this isn't really an issue. It seems that after updating Crystal from 0.22.0 to 0.23.0 the `shards build` compiler is now throwing an error regarding Crecto.

I have a model extending Crecto::Model. After the update, it can no longer find the method 'schema'.

Error is as follows -
```
in src/app/models/review.cr:7: undefined method 'schema'

  schema "reviews" do
```
Setup looks something like this -
```
class Review < Crecto::Model
  schema "reviews" do
  end
end
```
Let me know if I'm doing anything wrong or if I can be of help.

**Comment by fridgerator** [comment]
Just noticed this earlier today.  I'll have to figure out what broke with crystal 0.23.0 and will probably release a new version soon.

Thanks for the issue!

**Comment by metacortex** [comment]
https://github.com/crystal-lang/crystal/issues/4639

maybe crystal's bug

**Comment by fridgerator** [comment]
Yep, I think its an issue with the 0.23.0 release.  Going to wait for 0.23.1 (which I believe should be soon)

**Comment by hak8or** [comment]
Sadly based on the discussion in that bug report, it seems that they will [shift](https://github.com/crystal-lang/crystal/issues/4639#issuecomment-314878209) it over to not the next release but instead for a next next release.

They say there are workarounds, but I am not clear how to do the include based workaround (still new to crystal). Instead, I tried the following which was suggested:
```crystal
require "sqlite3"
require "crecto"

module SqliteRepo
  extend Crecto::Repo

  config do |conf|
    conf.adapter = Crecto::Adapters::SQLite3
    conf.database = "./database.db"
  end
end

#
# Define table name, fields and validations in your model
#
class User < Crecto::Model
  include Crecto::Schema
    Crecto::Schema.schema "users" do
    Crecto::Schema.field :age, Int32
  end
end
```

but compilation fails via below.
```crystal
crystalproj λ crystal src/browser.cr
Error in src/browser.cr:19: expanding macro

    Crecto::Schema.field :age, Int32
                   ^~~~~

in lib/crecto/src/crecto/schema.cr:107: undefined constant FIELDS

        {% FIELDS.push({name: field_name, type: field_type}) %}
           ^~~~~~

crystalproj λ 
```

**Comment by hak8or** [comment]
## Original post
Sorry for the lack of information on my part, I am still on ```Crystal 0.23.0 (2017-07-13) LLVM 4.0.1``` (waiting for Arch packages to update to ```0.23.1```) and ```crecto (0.6.1)```. 

I meant my post to show 
- The crystal team (via the hyperlink in said post) apparently will leave the fix for this for not 0.23.1 but instead the version after that.
- The recommended workaround for getting it to work with ```0.23.0``` doesn't seem to work for me.

It seems my only option is to wait for the crystal team to release the next version which includes the fix (```0.23.2``` I guess?). Or, is ```0.23.1``` supposed to have a fix for this?

## Master Branch
I tried using crystal compiled from the master branch but that seems to be ```Crystal 0.23.0+12 [944c0837c] (2017-07-15) LLVM 4.0.1``` (not sure why that doesn't say ```0.23.1```) but that returns the following for your example:
```crystal
crystalprojl λ /tmp/crystal/crystal/bin/crystal src/browser.cr 
Using compiled compiler at `.build/crystal'
Error in src/browser.cr:17: undefined method 'schema'

  schema "users" do
  ^~~~~~
```

Actually turns out master does not include ```0.23.1``` for some reason, hence why my version number from compiling the master branch was old. Instead, they have a separate [branch](https://github.com/crystal-lang/crystal/tree/0.23.1) for release. I did not try compiling that specific branch in the end.

## Most Recent Release
Using the most recent [release](https://github.com/crystal-lang/crystal/releases/tag/0.23.1) (```crystal-0.23.1-3-linux-x86_64.tar.gz``` which does indeed sem to be ```Crystal 0.23.1 [e2a1389e8] (2017-07-13) LLVM 3.8.1``` does actually work. I do not understand why this works when the crystal team said they are [shifting](https://github.com/crystal-lang/crystal/issues/4639#issuecomment-314878209) the fix to the next next version and they even removed the issue from the milestone.

## Conclusion
Sorry for the fuss, all is now fine. Crystal version ```0.23.1``` which can be found [here](https://github.com/crystal-lang/crystal/releases/tag/0.23.1) does work. Arch packages (both crystal and crystal-git) as of posting this are still on ```0.23.0```. I figure I will keep my post here as-is in case anyone else follows my route before arch or their distributions repositories update their version of crystal.

**Comment by fridgerator** [comment]
glad to hear its working for you 👍
