### PR TITLE
Fix crystal logger support

### PR DESCRIPTION
**Pull request by grig191**
Recently introduced by https://github.com/Crecto/crecto/commit/1e9bae0966626777f34d1e5e9d79c457cba45991 support of Crystal logger is broken giving following error:
```crystal
in lib/crecto/src/crecto/db_logger.cr:32: undefined method 'level=' for IO::ARGF (compile-time type is (IO | Logger | Nil))

      @@log_handler.level = Logger::INFO
```
But changing this line will fix all errors, including integration with [amber framework](https://github.com/amberframework/amber):
```crystal
@@log_handler.as(Logger).level = Logger::INFO
```

### CODE REVIEW

**Comment by fridgerator** [comment]
thanks! 👍
